name = "NonlinearExampleforBrownBag"
uuid = "46f9da73-e2f7-45c6-9c0e-78853dc245ed"
authors = ["David Stein"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
